# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from . import devices
from .. import _compat
from .shared import (
    Meta as Meta,
    Location as Location,
    DeviceSpec as DeviceSpec,
    Pagination as Pagination,
    DeviceCarrier as DeviceCarrier,
    PermissionSet as PermissionSet,
    PaginationMeta as PaginationMeta,
    DeviceIdentifiers as DeviceIdentifiers,
    Socks5ProxyConfig as Socks5ProxyConfig,
)
from .app_list_params import AppListParams as AppListParams
from .task_run_params import TaskRunParams as TaskRunParams
from .esim_list_params import EsimListParams as EsimListParams
from .file_list_params import FileListParams as FileListParams
from .task_list_params import TaskListParams as TaskListParams
from .app_list_response import AppListResponse as AppListResponse
from .proxy_list_params import ProxyListParams as ProxyListParams
from .task_run_response import TaskRunResponse as TaskRunResponse
from .device_list_params import DeviceListParams as DeviceListParams
from .esim_create_params import EsimCreateParams as EsimCreateParams
from .esim_import_params import EsimImportParams as EsimImportParams
from .esim_list_response import EsimListResponse as EsimListResponse
from .esim_update_params import EsimUpdateParams as EsimUpdateParams
from .file_list_response import FileListResponse as FileListResponse
from .file_update_params import FileUpdateParams as FileUpdateParams
from .mailbox_otp_params import MailboxOtpParams as MailboxOtpParams
from .number_list_params import NumberListParams as NumberListParams
from .task_list_response import TaskListResponse as TaskListResponse
from .task_stop_response import TaskStopResponse as TaskStopResponse
from .app_delete_response import AppDeleteResponse as AppDeleteResponse
from .carrier_list_params import CarrierListParams as CarrierListParams
from .esim_install_params import EsimInstallParams as EsimInstallParams
from .mailbox_list_params import MailboxListParams as MailboxListParams
from .message_list_params import MessageListParams as MessageListParams
from .model_list_response import ModelListResponse as ModelListResponse
from .profile_list_params import ProfileListParams as ProfileListParams
from .proxy_create_params import ProxyCreateParams as ProxyCreateParams
from .proxy_list_response import ProxyListResponse as ProxyListResponse
from .proxy_lookup_params import ProxyLookupParams as ProxyLookupParams
from .proxy_update_params import ProxyUpdateParams as ProxyUpdateParams
from .webhook_list_params import WebhookListParams as WebhookListParams
from .device_create_params import DeviceCreateParams as DeviceCreateParams
from .device_list_response import DeviceListResponse as DeviceListResponse
from .esim_create_response import EsimCreateResponse as EsimCreateResponse
from .esim_import_response import EsimImportResponse as EsimImportResponse
from .esim_selector_params import EsimSelectorParams as EsimSelectorParams
from .esim_update_response import EsimUpdateResponse as EsimUpdateResponse
from .file_delete_response import FileDeleteResponse as FileDeleteResponse
from .file_update_response import FileUpdateResponse as FileUpdateResponse
from .mailbox_otp_response import MailboxOtpResponse as MailboxOtpResponse
from .number_create_params import NumberCreateParams as NumberCreateParams
from .number_list_response import NumberListResponse as NumberListResponse
from .number_update_params import NumberUpdateParams as NumberUpdateParams
from .app_event_list_params import AppEventListParams as AppEventListParams
from .app_retrieve_response import AppRetrieveResponse as AppRetrieveResponse
from .carrier_create_params import CarrierCreateParams as CarrierCreateParams
from .carrier_list_response import CarrierListResponse as CarrierListResponse
from .carrier_lookup_params import CarrierLookupParams as CarrierLookupParams
from .carrier_update_params import CarrierUpdateParams as CarrierUpdateParams
from .device_count_response import DeviceCountResponse as DeviceCountResponse
from .esim_install_response import EsimInstallResponse as EsimInstallResponse
from .file_confirm_response import FileConfirmResponse as FileConfirmResponse
from .mailbox_create_params import MailboxCreateParams as MailboxCreateParams
from .mailbox_list_response import MailboxListResponse as MailboxListResponse
from .mailbox_update_params import MailboxUpdateParams as MailboxUpdateParams
from .message_list_response import MessageListResponse as MessageListResponse
from .profile_create_params import ProfileCreateParams as ProfileCreateParams
from .profile_list_response import ProfileListResponse as ProfileListResponse
from .profile_update_params import ProfileUpdateParams as ProfileUpdateParams
from .proxy_create_response import ProxyCreateResponse as ProxyCreateResponse
from .proxy_delete_response import ProxyDeleteResponse as ProxyDeleteResponse
from .proxy_lookup_response import ProxyLookupResponse as ProxyLookupResponse
from .proxy_update_response import ProxyUpdateResponse as ProxyUpdateResponse
from .webhook_create_params import WebhookCreateParams as WebhookCreateParams
from .webhook_list_response import WebhookListResponse as WebhookListResponse
from .webhook_update_params import WebhookUpdateParams as WebhookUpdateParams
from .credential_list_params import CredentialListParams as CredentialListParams
from .device_create_response import DeviceCreateResponse as DeviceCreateResponse
from .device_set_name_params import DeviceSetNameParams as DeviceSetNameParams
from .esim_capacity_response import EsimCapacityResponse as EsimCapacityResponse
from .esim_retrieve_response import EsimRetrieveResponse as EsimRetrieveResponse
from .esim_selector_response import EsimSelectorResponse as EsimSelectorResponse
from .file_upload_url_params import FileUploadURLParams as FileUploadURLParams
from .mailbox_restart_params import MailboxRestartParams as MailboxRestartParams
from .number_create_response import NumberCreateResponse as NumberCreateResponse
from .number_delete_response import NumberDeleteResponse as NumberDeleteResponse
from .number_update_response import NumberUpdateResponse as NumberUpdateResponse
from .task_retrieve_response import TaskRetrieveResponse as TaskRetrieveResponse
from .app_event_list_response import AppEventListResponse as AppEventListResponse
from .carrier_create_response import CarrierCreateResponse as CarrierCreateResponse
from .carrier_delete_response import CarrierDeleteResponse as CarrierDeleteResponse
from .carrier_lookup_response import CarrierLookupResponse as CarrierLookupResponse
from .carrier_update_response import CarrierUpdateResponse as CarrierUpdateResponse
from .device_terminate_params import DeviceTerminateParams as DeviceTerminateParams
from .mailbox_create_response import MailboxCreateResponse as MailboxCreateResponse
from .mailbox_delete_response import MailboxDeleteResponse as MailboxDeleteResponse
from .mailbox_update_response import MailboxUpdateResponse as MailboxUpdateResponse
from .profile_create_response import ProfileCreateResponse as ProfileCreateResponse
from .profile_delete_response import ProfileDeleteResponse as ProfileDeleteResponse
from .profile_update_response import ProfileUpdateResponse as ProfileUpdateResponse
from .proxy_retrieve_response import ProxyRetrieveResponse as ProxyRetrieveResponse
from .webhook_create_response import WebhookCreateResponse as WebhookCreateResponse
from .webhook_update_response import WebhookUpdateResponse as WebhookUpdateResponse
from .app_mark_failed_response import AppMarkFailedResponse as AppMarkFailedResponse
from .credential_list_response import CredentialListResponse as CredentialListResponse
from .device_retrieve_response import DeviceRetrieveResponse as DeviceRetrieveResponse
from .device_set_name_response import DeviceSetNameResponse as DeviceSetNameResponse
from .file_upload_url_response import FileUploadURLResponse as FileUploadURLResponse
from .mailbox_restart_response import MailboxRestartResponse as MailboxRestartResponse
from .number_purposes_response import NumberPurposesResponse as NumberPurposesResponse
from .number_retrieve_response import NumberRetrieveResponse as NumberRetrieveResponse
from .task_get_status_response import TaskGetStatusResponse as TaskGetStatusResponse
from .task_run_streamed_params import TaskRunStreamedParams as TaskRunStreamedParams
from .task_send_message_params import TaskSendMessageParams as TaskSendMessageParams
from .carrier_retrieve_response import CarrierRetrieveResponse as CarrierRetrieveResponse
from .mailbox_capacity_response import MailboxCapacityResponse as MailboxCapacityResponse
from .mailbox_retrieve_response import MailboxRetrieveResponse as MailboxRetrieveResponse
from .mailbox_uncancel_response import MailboxUncancelResponse as MailboxUncancelResponse
from .number_countries_response import NumberCountriesResponse as NumberCountriesResponse
from .profile_retrieve_response import ProfileRetrieveResponse as ProfileRetrieveResponse
from .store_categories_response import StoreCategoriesResponse as StoreCategoriesResponse
from .webhook_retrieve_response import WebhookRetrieveResponse as WebhookRetrieveResponse
from .app_list_versions_response import AppListVersionsResponse as AppListVersionsResponse
from .app_storage_usage_response import AppStorageUsageResponse as AppStorageUsageResponse
from .device_wait_ready_response import DeviceWaitReadyResponse as DeviceWaitReadyResponse
from .task_send_message_response import TaskSendMessageResponse as TaskSendMessageResponse
from .app_confirm_upload_response import AppConfirmUploadResponse as AppConfirmUploadResponse
from .app_event_retrieve_response import AppEventRetrieveResponse as AppEventRetrieveResponse
from .device_fingerprint_response import DeviceFingerprintResponse as DeviceFingerprintResponse
from .esim_install_status_response import EsimInstallStatusResponse as EsimInstallStatusResponse
from .file_cancel_pending_response import FileCancelPendingResponse as FileCancelPendingResponse
from .task_get_trajectory_response import TaskGetTrajectoryResponse as TaskGetTrajectoryResponse
from .webhook_event_types_response import WebhookEventTypesResponse as WebhookEventTypesResponse
from .esim_confirm_payment_response import EsimConfirmPaymentResponse as EsimConfirmPaymentResponse
from .notification_catalog_response import NotificationCatalogResponse as NotificationCatalogResponse
from .webhook_rotate_secret_response import WebhookRotateSecretResponse as WebhookRotateSecretResponse
from .webhook_test_delivery_response import WebhookTestDeliveryResponse as WebhookTestDeliveryResponse
from .app_create_signed_upload_url_params import AppCreateSignedUploadURLParams as AppCreateSignedUploadURLParams
from .app_create_signed_upload_url_response import AppCreateSignedUploadURLResponse as AppCreateSignedUploadURLResponse
from .device_retrieve_capabilities_response import (
    DeviceRetrieveCapabilitiesResponse as DeviceRetrieveCapabilitiesResponse,
)
from .notification_get_preferences_response import (
    NotificationGetPreferencesResponse as NotificationGetPreferencesResponse,
)
from .notification_update_preferences_params import (
    NotificationUpdatePreferencesParams as NotificationUpdatePreferencesParams,
)
from .notification_update_preferences_response import (
    NotificationUpdatePreferencesResponse as NotificationUpdatePreferencesResponse,
)

# Rebuild cyclical models only after all modules are imported.
# This ensures that, when building the deferred (due to cyclical references) model schema,
# Pydantic can resolve the necessary references.
# See: https://github.com/pydantic/pydantic/issues/11250 for more context.
if _compat.PYDANTIC_V1:
    devices.a11_y_node.A11YNode.update_forward_refs()  # type: ignore
    devices.state_ui_response.StateUiResponse.update_forward_refs()  # type: ignore
else:
    devices.a11_y_node.A11YNode.model_rebuild(_parent_namespace_depth=0)
    devices.state_ui_response.StateUiResponse.model_rebuild(_parent_namespace_depth=0)
