# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .. import _compat

from . import devices

from .shared import DeviceCarrier as DeviceCarrier, DeviceIdentifiers as DeviceIdentifiers, DeviceSpec as DeviceSpec, Location as Location, Meta as Meta, Pagination as Pagination, PaginationMeta as PaginationMeta, PermissionSet as PermissionSet, Socks5ProxyConfig as Socks5ProxyConfig
from .app_retrieve_response import AppRetrieveResponse as AppRetrieveResponse
from .app_list_response import AppListResponse as AppListResponse
from .app_delete_response import AppDeleteResponse as AppDeleteResponse
from .app_confirm_upload_response import AppConfirmUploadResponse as AppConfirmUploadResponse
from .app_create_signed_upload_url_response import AppCreateSignedUploadURLResponse as AppCreateSignedUploadURLResponse
from .app_list_versions_response import AppListVersionsResponse as AppListVersionsResponse
from .app_mark_failed_response import AppMarkFailedResponse as AppMarkFailedResponse
from .app_storage_usage_response import AppStorageUsageResponse as AppStorageUsageResponse
from .app_list_params import AppListParams as AppListParams
from .app_create_signed_upload_url_params import AppCreateSignedUploadURLParams as AppCreateSignedUploadURLParams
from .carrier_create_response import CarrierCreateResponse as CarrierCreateResponse
from .carrier_retrieve_response import CarrierRetrieveResponse as CarrierRetrieveResponse
from .carrier_update_response import CarrierUpdateResponse as CarrierUpdateResponse
from .carrier_list_response import CarrierListResponse as CarrierListResponse
from .carrier_delete_response import CarrierDeleteResponse as CarrierDeleteResponse
from .carrier_lookup_response import CarrierLookupResponse as CarrierLookupResponse
from .carrier_create_params import CarrierCreateParams as CarrierCreateParams
from .carrier_update_params import CarrierUpdateParams as CarrierUpdateParams
from .carrier_list_params import CarrierListParams as CarrierListParams
from .carrier_lookup_params import CarrierLookupParams as CarrierLookupParams
from .credential_list_response import CredentialListResponse as CredentialListResponse
from .credential_list_params import CredentialListParams as CredentialListParams
from .device_create_response import DeviceCreateResponse as DeviceCreateResponse
from .device_retrieve_response import DeviceRetrieveResponse as DeviceRetrieveResponse
from .device_list_response import DeviceListResponse as DeviceListResponse
from .device_count_response import DeviceCountResponse as DeviceCountResponse
from .device_fingerprint_response import DeviceFingerprintResponse as DeviceFingerprintResponse
from .device_retrieve_capabilities_response import DeviceRetrieveCapabilitiesResponse as DeviceRetrieveCapabilitiesResponse
from .device_set_name_response import DeviceSetNameResponse as DeviceSetNameResponse
from .device_wait_ready_response import DeviceWaitReadyResponse as DeviceWaitReadyResponse
from .device_create_params import DeviceCreateParams as DeviceCreateParams
from .device_list_params import DeviceListParams as DeviceListParams
from .device_set_name_params import DeviceSetNameParams as DeviceSetNameParams
from .device_terminate_params import DeviceTerminateParams as DeviceTerminateParams
from .model_list_response import ModelListResponse as ModelListResponse
from .profile_create_response import ProfileCreateResponse as ProfileCreateResponse
from .profile_retrieve_response import ProfileRetrieveResponse as ProfileRetrieveResponse
from .profile_update_response import ProfileUpdateResponse as ProfileUpdateResponse
from .profile_list_response import ProfileListResponse as ProfileListResponse
from .profile_delete_response import ProfileDeleteResponse as ProfileDeleteResponse
from .profile_create_params import ProfileCreateParams as ProfileCreateParams
from .profile_update_params import ProfileUpdateParams as ProfileUpdateParams
from .profile_list_params import ProfileListParams as ProfileListParams
from .proxy_create_response import ProxyCreateResponse as ProxyCreateResponse
from .proxy_retrieve_response import ProxyRetrieveResponse as ProxyRetrieveResponse
from .proxy_update_response import ProxyUpdateResponse as ProxyUpdateResponse
from .proxy_list_response import ProxyListResponse as ProxyListResponse
from .proxy_delete_response import ProxyDeleteResponse as ProxyDeleteResponse
from .proxy_lookup_response import ProxyLookupResponse as ProxyLookupResponse
from .proxy_create_params import ProxyCreateParams as ProxyCreateParams
from .proxy_update_params import ProxyUpdateParams as ProxyUpdateParams
from .proxy_list_params import ProxyListParams as ProxyListParams
from .proxy_lookup_params import ProxyLookupParams as ProxyLookupParams
from .task_retrieve_response import TaskRetrieveResponse as TaskRetrieveResponse
from .task_list_response import TaskListResponse as TaskListResponse
from .task_get_status_response import TaskGetStatusResponse as TaskGetStatusResponse
from .task_get_trajectory_response import TaskGetTrajectoryResponse as TaskGetTrajectoryResponse
from .task_run_response import TaskRunResponse as TaskRunResponse
from .task_send_message_response import TaskSendMessageResponse as TaskSendMessageResponse
from .task_stop_response import TaskStopResponse as TaskStopResponse
from .task_list_params import TaskListParams as TaskListParams
from .task_run_params import TaskRunParams as TaskRunParams
from .task_run_streamed_params import TaskRunStreamedParams as TaskRunStreamedParams
from .task_send_message_params import TaskSendMessageParams as TaskSendMessageParams
from .webhook_create_response import WebhookCreateResponse as WebhookCreateResponse
from .webhook_retrieve_response import WebhookRetrieveResponse as WebhookRetrieveResponse
from .webhook_update_response import WebhookUpdateResponse as WebhookUpdateResponse
from .webhook_list_response import WebhookListResponse as WebhookListResponse
from .webhook_event_types_response import WebhookEventTypesResponse as WebhookEventTypesResponse
from .webhook_rotate_secret_response import WebhookRotateSecretResponse as WebhookRotateSecretResponse
from .webhook_test_delivery_response import WebhookTestDeliveryResponse as WebhookTestDeliveryResponse
from .webhook_create_params import WebhookCreateParams as WebhookCreateParams
from .webhook_update_params import WebhookUpdateParams as WebhookUpdateParams
from .webhook_list_params import WebhookListParams as WebhookListParams
from .agent_list_response import AgentListResponse as AgentListResponse
from .app_event_retrieve_response import AppEventRetrieveResponse as AppEventRetrieveResponse
from .app_event_list_response import AppEventListResponse as AppEventListResponse
from .app_event_list_params import AppEventListParams as AppEventListParams
from .notification_catalog_response import NotificationCatalogResponse as NotificationCatalogResponse
from .notification_get_preferences_response import NotificationGetPreferencesResponse as NotificationGetPreferencesResponse
from .notification_update_preferences_response import NotificationUpdatePreferencesResponse as NotificationUpdatePreferencesResponse
from .notification_update_preferences_params import NotificationUpdatePreferencesParams as NotificationUpdatePreferencesParams
from .esim_create_response import EsimCreateResponse as EsimCreateResponse
from .esim_retrieve_response import EsimRetrieveResponse as EsimRetrieveResponse
from .esim_update_response import EsimUpdateResponse as EsimUpdateResponse
from .esim_list_response import EsimListResponse as EsimListResponse
from .esim_capacity_response import EsimCapacityResponse as EsimCapacityResponse
from .esim_confirm_payment_response import EsimConfirmPaymentResponse as EsimConfirmPaymentResponse
from .esim_import_response import EsimImportResponse as EsimImportResponse
from .esim_install_response import EsimInstallResponse as EsimInstallResponse
from .esim_install_status_response import EsimInstallStatusResponse as EsimInstallStatusResponse
from .esim_selector_response import EsimSelectorResponse as EsimSelectorResponse
from .esim_create_params import EsimCreateParams as EsimCreateParams
from .esim_update_params import EsimUpdateParams as EsimUpdateParams
from .esim_list_params import EsimListParams as EsimListParams
from .esim_import_params import EsimImportParams as EsimImportParams
from .esim_install_params import EsimInstallParams as EsimInstallParams
from .message_list_response import MessageListResponse as MessageListResponse
from .message_list_params import MessageListParams as MessageListParams
from .number_create_response import NumberCreateResponse as NumberCreateResponse
from .number_retrieve_response import NumberRetrieveResponse as NumberRetrieveResponse
from .number_list_response import NumberListResponse as NumberListResponse
from .number_delete_response import NumberDeleteResponse as NumberDeleteResponse
from .number_countries_response import NumberCountriesResponse as NumberCountriesResponse
from .number_purposes_response import NumberPurposesResponse as NumberPurposesResponse
from .number_create_params import NumberCreateParams as NumberCreateParams
from .number_list_params import NumberListParams as NumberListParams
from .store_categories_response import StoreCategoriesResponse as StoreCategoriesResponse

# Rebuild cyclical models only after all modules are imported.
# This ensures that, when building the deferred (due to cyclical references) model schema,
# Pydantic can resolve the necessary references.
# See: https://github.com/pydantic/pydantic/issues/11250 for more context.
if _compat.PYDANTIC_V1:
    devices.a11_y_node.A11YNode.update_forward_refs()  # type: ignore
    devices.state_ui_response.StateUiResponse.update_forward_refs()  # type: ignore
else:
    devices.a11_y_node.A11YNode.model_rebuild(_parent_namespace_depth=0)
    devices.state_ui_response.StateUiResponse.model_rebuild(_parent_namespace_depth=0)